'\" t
.\"     Title: sunshine
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 10/06/2015
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "SUNSHINE" "8" "10/06/2015" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
sunshine \- light up RPL DAG
.SH "SYNOPSIS"
.HP \w'\fBsunshine\fR\ 'u
\fBsunshine\fR interface [\fIwlan0\fR] dagid [\fI0xabcd1234abcd1234\fR] prefix [\fIfd01:abcd::/32\fR] rank [\fI1\fR] instanceid [\fI1\fR] interval [\fI20000\fR] ignore\-pio dao\-if\-filter [\fIacp*\fR] dao\-addr\-filter [\fIfd01::/16\fR] syslog stderr
.SH "EXAMPLES"
.HP \w'\fBsunshine\fR\ 'u
\fBsunshine\fR \-\-dagid \fIfunfun0\fR \-\-rank \fI1\fR \-\-prefix \fI2001:db8:0001::/48\fR \-\-interface \fIeth1\fR \-\-interval \fI30000\fR \-\-timelog \-\-verbose
.HP \w'\fBsunshine\fR\ 'u
\fBsunshine\fR \-\-dagid \fIfunfun0\fR \-\-interface \fIeth0\fR \-\-interval \fI60000\fR \-\-timelog \-\-verbose
.HP \w'\fBsunshine\fR\ 'u
\fBsunshine\fR \-\-dagid \fIfunfun0\fR \-\-interface \fIwlan0\fR \-\-ignore\-pio \-\-dao\-if\-filter \fIacp*\fR \-\-dao\-addr\-filter \fIfd04:ec6f:d73f::/48\fR \-\-timelog \-\-verbose
.SH "DESCRIPTION"
.PP
\fIsunshine\fR
is a daemon that runs on an RPL node that intends to forward packets, and act as a grounded node in an RPL DAG\&.
.SH "FILES"
.PP
file1
.SH "SEE ALSO"
.PP
\fBping6\fR(8),
.SH "DIAGNOSTICS"
.PP
All output from the commands
.SH "HISTORY"
.PP
Written for the Pandora Unstrung project <\m[blue]\fBhttp://unstrung\&.sandelman\&.ca\fR\m[]> by Michael Richardson around 2009\-11\-09
.SH "BUGS"
.PP
No known bugs\&.
