# the cp for the libcrypto modules keeps us from using the containers.
sudo: required
dist: trusty

language: c++
compiler:
  - g++

cache:
  directories:
  - $HOME/stuff

before_install:
  - "sudo dpkg --add-architecture i386"
  - "sudo apt-get update"
  - "sudo apt-get remove oracle-java7-installer oracle-java8-installer"

# the cp is because libssl-dev:i386 and libssl-dev:amd64 can not co-exist together due to package
# incompatibilities, but in fact have no problems in practice.
install:
  - "sudo ./install-apt-deps.sh"
  - "./build-setup-travis.sh"
  - "PATH=$HOME/bin:$PATH export PATH"

script:
  - "cat Makefile.local"
  - "make vars "
  - "make programs "
  - "make checkprograms "
  - "make unitcheck"
