language: c++
compiler:
  - gcc
  - g++

before_install:
  - "echo sudo dpkg --add-architecture i386"
  - "echo sudo apt-get update"

install:
  - "sudo apt-get install gcc-multilib g++-multilib tcpdump"
  - "sudo apt-get install build-essential lib32stdc++6 libusb-1.0-0-dev:i386 lib32z1-dev libpcap0.8-dev:i386"

script:
  - "make programs"
  - "make unitcheck"
