language: c++
compiler:
  - g++

before_install:
  - "sudo apt-get update"
  - "sudo apt-get remove oracle-java7-installer oracle-java8-installer"

install:
  - "sudo apt-get install gcc-multilib g++-multilib pkg-config"
  - "sudo apt-get install build-essential lib32stdc++6 libusb-1.0-0-dev:i386 lib32z1-dev flex bison libssl-dev:i386"
  - "(cd .. && curl http://www.tcpdump.org/release/libpcap-1.6.1.tar.gz | tar xzf - )"
  - "(cd .. && curl http://www.tcpdump.org/release/tcpdump-4.6.1.tar.gz | tar xzf - )"
  - "(cd .. && mkdir -p host/libpcap-1.6.1 && cd host/libpcap-1.6.1 && ../../libpcap-1.6.1/configure && make && sudo make install )"
  - "(cd .. && mkdir -p host/tcpdump-4.6.1 && cd host/tcpdump-4.6.1 && ../../tcpdump-4.6.1/configure && make && sudo make install )"
  - "(cd .. && mkdir -p x86/libpcap-1.6.1 && cd x86/libpcap-1.6.1 && ../../libpcap-1.6.1/configure && make)"
  - "(cd .. && mkdir -p x86/tcpdump-4.6.1 && cd x86/tcpdump-4.6.1 && ../../tcpdump-4.6.1/configure && make)"

script:
  - "echo LIBPCAP=$(pwd)/../x86/libpcap-1.6.1 >Makefile.local"
  - "echo NETDISSECTLIB=$(pwd)/../host/tcpdump-1.6.1/libnetdissect.a >>Makefile.local"
  - "make programs "
  - "make checkprograms "
  - "make unitcheck"
