language: c++
compiler:
  - g++

before_install:
  - "sudo apt-get update"
  - "sudo apt-get remove oracle-java7-installer oracle-java8-installer"

install:
  - "sudo apt-get install gcc-multilib g++-multilib pkg-config"
  - "sudo apt-get install build-essential lib32stdc++6 libusb-1.0-0-dev:i386 lib32z1-dev flex bison libssl-dev:i386"
  - "(cd .. && curl http://www.tcpdump.org/release/libpcap-1.6.1.tar.gz | tar xzf - )"
  - "(cd .. && curl http://www.tcpdump.org/release/tcpdump-4.6.1.tar.gz | tar xzf - )"
  - "(cd .. && mkdir -p libpcap-1.6.1-host && cd libpcap-1.6.1-host && ../libpcap-1.6.1/configure && make && sudo make install )"
  - "(cd .. && mkdir -p tcpdump-4.6.1-host && cd tcpdump-4.6.1-host && ../tcpdump-4.6.1/configure && make && sudo make install )"
  - "(cd .. && mkdir -p libpcap-1.6.1-x86 && cd libpcap-1.6.1-x86 && ../libpcap-1.6.1/configure && make)"
  - "(cd .. && mkdir -p tcpdump-4.6.1-x86 && cd tcpdump-4.6.1-x86 && ../tcpdump-4.6.1/configure --with-libpcap=../libpcap-1.6.1-x86 && make)"

script:
  - "make programs"
  - "make checkprograms"
  - "make unitcheck"
