# the cp for the libcrypto modules keeps us from using the containers.
sudo: required

language: c++
compiler:
  - g++

cache:
  directories:
  - $HOME/stuff

before_install:
  - "sudo apt-get update"
  - "sudo apt-get remove oracle-java7-installer oracle-java8-installer"

# the cp is because libssl-dev:i386 and libssl-dev:amd64 can not co-exist together due to package
# incompatibilities, but in fact have no problems in practice.
install:
  - "sudo apt-get install gcc-multilib g++-multilib pkg-config libssl1.0.0 libssl-dev"
  - "sudo cp /usr/lib/x86_64-linux-gnu/libcrypto* /tmp"
  - "sudo apt-get install build-essential lib32stdc++6 libusb-1.0-0-dev:i386 lib32z1-dev flex bison libssl-dev:i386 libboose1.49-dev"
  - "sudo mv /tmp/libcrypto* /usr/lib/x86_64-linux-gnu"
  - "./build-setup-travis.sh"
  - "PATH=$HOME/bin:$PATH export PATH"

script:
  - "cat Makefile.local"
  - "make vars "
  - "make programs "
  - "make checkprograms "
  - "make unitcheck"
