language: c++
compiler:
  - g++

before_install:
  - "sudo apt-get update"
  - "sudo apt-get remove oracle-java7-installer oracle-java8-installer"

install:
  - "sudo apt-get install gcc-multilib g++-multilib pkg-config libssl1.0.0 libssl-dev"
  - "sudo cp /usr/lib/x86_64-linux-gnu/libcrypto* /tmp"
  - "sudo apt-get install build-essential lib32stdc++6 libusb-1.0-0-dev:i386 lib32z1-dev flex bison libssl-dev:i386"
  - "sudo mv /tmp/libcrypto* /usr/lib/x86_64-linux-gnu"
  - "(cd .. && curl http://www.ca.tcpdump.org/release/libpcap-1.6.2.tar.gz | tar xzf - )"
  - "(cd .. && curl http://www.ca.tcpdump.org/release/tcpdump-4.6.2.tar.gz | tar xzf - )"
  - "(cd .. && mkdir -p host/libpcap-1.6.2 && cd host/libpcap-1.6.2 && ../../libpcap-1.6.2/configure && make && sudo make install )"
  - "(cd .. && mkdir -p host/tcpdump-4.6.2 && cd host/tcpdump-4.6.2 && ../../tcpdump-4.6.2/configure && make && sudo make install )"
  - "(cd .. && mkdir -p x86/libpcap-1.6.2 && cd x86/libpcap-1.6.2 && CFLAGS=-m32 ../../libpcap-1.6.2/configure --target=i686-pc-linux-gnu && make LDFLAGS=-m32 CFLAGS=-m32)"
  - "(cd .. && ln -s x86/libpcap-1.6.2 libpcap && mkdir -p x86/tcpdump-4.6.2 && cd x86/tcpdump-4.6.2 && CFLAGS=-m32 ../../tcpdump-4.6.2/configure --target=i686-pc-linux-gnu && make LDFLAGS=-m32 CFLAGS=-m32)"

script:
  - "echo LIBPCAP=$(pwd)/../x86/libpcap-1.6.2/libpcap.a >Makefile.local"
  - "echo TCPDUMP=$(pwd)/../host/tcpdump-4.6.2/tcpdump  >>Makefile.local"
  - "echo NETDISSECTLIB=$(pwd)/../host/tcpdump-4.6.2/libnetdissect.a >>Makefile.local"
  - "echo NETDISSECTH=-DNETDISSECT -I$(pwd)/../host/tcpdump-4.6.2/ -I$(pwd)/../tcpdump-4.6.2 >>Makefile.local"
  - "cat Makefile.local"
  - "make vars "
  - "make programs "
  - "make checkprograms "
  - "make unitcheck"
