# -*- makefile -*-
# Pandora master makefile
#
# Copyright (C) 2009 Michael Richardson <mcr@sandelman.ca>
#
# This program is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by the
# Free Software Foundation; either version 2 of the License, or (at your
# option) any later version.  See <http://www.fsf.org/copyleft/gpl.txt>.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# for more details.
#
# RCSID $Id: Makefile.top,v 1.4 2005/07/18 03:46:13 mcr Exp $

NEEDCHECK:=
MAKEFILETOP:=true
SUBDIRS=lib programs testing
VDE_DIR=${UNSTRUNG_SRCDIR}/UMLPOOL/.vde

clean::
	-echo cleaning

distclean:	clean
	if [ -f umlsetup.sh ]; then source umlsetup.sh; if [ -d "$$POOLSPACE" ]; then rm -rf $$POOLSPACE; fi; fi

uml:	checkprograms virtualmachines

virtualmachines:
	echo MORE DO TO.

checkprograms::
	@for d in $(SUBDIRS); do (cd $$d && $(MAKE) DESTDIR=${DESTDIR} checkprograms || exit 1); done

check::	Makefile.ver
ifneq ($(strip(${REGRESSRESULTS})),)
	mkdir -p ${REGRESSRESULTS}
endif
	@for d in $(SUBDIRS); \
	do \
		echo ===================================; \
		echo Now making check in $$d; \
		echo ===================================; \
		(cd $$d && $(MAKE) DESTDIR=${DESTDIR} check || exit 1);\
	done
ifneq ($(strip(${REGRESSRESULTS})),)
	-perl testing/utils/regress-summarize-results.pl ${REGRESSRESULTS}
endif

unitcheck:: Makefile.ver
	@for d in $(SUBDIRS); \
	do \
		(cd $$d && $(MAKE) DESTDIR=${DESTDIR} unitcheck || exit 1);\
	done

TAGS::
	@rm -f TAGS
	@echo >TAGS

vars:
	@echo LIBPCAP: ${LIBPCAP}
	@echo TCPDUMP: ${TCPDUMP}
	@echo NETDISSECTLIB: ${NETDISSECTLIB}
	@echo USE_OBJDIR: ${USE_OBJDIR}
	@echo OBJDIR: ${OBJDIR}
	@echo ARCH: ${ARCH}
	@echo USERLINK: ${USERLINK}

version:
	@echo ${PANDORA_VERSION}

distarchive:
	git archive --prefix=unstrung-${PANDORA_VERSION}/ -o ../downloads/unstrung-${PANDORA_VERSION}.tar.gz HEAD

vde:
	mkdir -p ${VDE_DIR}/0 ${VDE_DIR}/1 ${VDE_DIR}/2 ${VDE_DIR}/3 ${VDE_DIR}/4 ${VDE_DIR}/99
	vde_switch -f testing/utils/vde99_script.rc -daemon -M ${VDE_DIR}/control99 -sock ${VDE_DIR}/99 -tap unstrung0
	vde_switch -f testing/utils/vde0_script.rc -daemon -M ${VDE_DIR}/control0 -sock ${VDE_DIR}/0
	vde_switch -f testing/utils/vde1_script.rc -daemon -M ${VDE_DIR}/control1 -sock ${VDE_DIR}/1
	vde_switch -f testing/utils/vde2_script.rc -daemon -M ${VDE_DIR}/control2 -sock ${VDE_DIR}/2
	vde_switch -f testing/utils/vde3_script.rc -daemon -M ${VDE_DIR}/control3 -sock ${VDE_DIR}/3
	vde_switch -f testing/utils/vde4_script.rc -daemon -M ${VDE_DIR}/control4 -sock ${VDE_DIR}/4

vde_console:
	unixterm ${UNSTRUNG_SRCDIR}/.vdecontrol

# export USE_ variables
export USE_OBJDIR

