UNSTRUNG_SRCDIR?=$(shell cd ../../..; pwd)

all: check

include ${UNSTRUNG_SRCDIR}/Makefile.inc
include ${srcdir}../Makefile.testing

TESTNAME=34-builddis
OUTPUT=node-E-dis
NUM=34

${TESTNAME}: ${TESTNAME}.cpp ${INC}/iface.h ${INC}/dag.h ${LIBNDMGMT}
	${CXX} ${CXXFLAGS} -o ${TESTNAME} ${TESTNAME}.cpp ${LDFLAGS}

check::	${TESTNAME}
	./${TESTNAME} | tee ../OUTPUTS/${OUTPUT}-out.txt | diff - ${OUTPUT}-out.txt
	@${TCPDUMP} -t -n -r ../OUTPUTS/${NUM}-${OUTPUT}.pcap | tee ../OUTPUTS/${OUTPUT}.txt | diff - ${OUTPUT}.txt

checkprograms:: ${TESTNAME}
programs::

clean::
	@rm -rf ${TESTNAME} *.o

update:
	cp ../OUTPUTS/${OUTPUT}-out.txt ${OUTPUT}-out.txt
	cp ../OUTPUTS/${OUTPUT}.txt ${OUTPUT}.txt

# Local Variables:
# compile-command: "make check"
# End:
