.\"     Title: peck
.\"    Author: 
.\" Generator: DocBook XSL Stylesheets v1.73.2 <http://docbook.sf.net/>
.\"      Date: 11/09/2009
.\"    Manual: 09 november 2009
.\"    Source: 09 november 2009
.\"
.TH "PECK" "8" "11/09/2009" "09 november 2009" "09 november 2009"
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.SH "NAME"
peck \- send arbitrary RPL DIO messages
.SH "SYNOPSIS"
.HP 5
\fBpeck\fR \fIsetup\fR [\-\-show | \-\-showonly] \fIcommand\fR
.SH "EXAMPLES"
.HP 6
\fBipsec\fR \fIsetup\fR [[\ \-\-showonly\ ]] {\ \-\-start\ |\ \-\-stop\ |\ \-\-restart\ }
.HP 6
\fBipsec\fR \fIsetup\fR \-\-status
.SH "DESCRIPTION"
.PP
\fIpeck\fR
opens an ICMPv6 socket and dumps any ICMPv6 messages seen\&.
.SH "FILES"
.PP
file1
.SH "SEE ALSO"
.PP
\fBping6\fR(8),
.SH "DIAGNOSTICS"
.PP
All output from the commands
.SH "HISTORY"
.PP
Written for the Pandora Unstrung project <\fIhttp://pandora\&.sandelman\&.ca\fR> by Michael Richardson\&.
.SH "BUGS"
.PP
No known bugs\&.
