.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "SENDND" "8" "September 2016" "" ""
.
.SH "NAME"
\fBsendnd\fR \- send 6lowPAN Neighbour Discovery messages
.
.P
The sendnd creates a number of different ND messages and sends them to a specified host or multicast address\. It then listens for ND messages for a period of time, and then exits\.
