INC=${UNSTRUNG_SRCDIR}/include

# local install of pcap.h, or make sure you have libpcap-dev installed.
CXXFLAGS+=${LIBPCAPINC} -g ${CROSSFLAGS}
CFLAGS+=${CROSSFLAGS}
LIBS=${LIBFAKEIFACE} ${LIBNDMGMT} ${LIBOSW} ${LIBNETLINK} ${LIBOSW}
LIBS+=${LIBGRASP}
LDFLAGS+=${LIBS} ${LIBPCAP} ${EXTRALIBS}
