'\" t
.\"     Title: senddao
.\"    Author: [FIXME: author] [see http://docbook.sf.net/el/author]
.\" Generator: DocBook XSL Stylesheets v1.76.1 <http://docbook.sf.net/>
.\"      Date: 10/07/2014
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "SENDDAO" "8" "10/07/2014" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
senddao \- send arbitrary RPL DAO messages
.SH "SYNOPSIS"
.HP \w'\fBsenddao\fR\ 'u
\fBsenddao\fR
.SH "EXAMPLES"
.HP \w'\fBsenddao\fR\ 'u
\fBsenddao\fR
.SH "DESCRIPTION"
.PP
\fIsenddao\fR
opens an ICMPv6 socket and sends arbitrary DAO messages onto the network\&.
.SH "FILES"
.PP
file1
.SH "SEE ALSO"
.PP
\fBping6\fR(8),
.SH "DIAGNOSTICS"
.PP
All output from the commands
.SH "HISTORY"
.PP
Written for the Pandora Unstrung project <\m[blue]\fBhttp://unstrung\&.sandelman\&.ca\fR\m[]> by Michael Richardson\&.
.SH "BUGS"
.PP
No known bugs\&.
