# xmlto is from http://cyberelk.net/tim/xmlto/
ifneq ($(strip $(XMLTO)),)
%.8: %.8.xml
	${XMLTO} man $<

%.8.html: %.8.xml
	${XMLTO} html-nochunks $<

%.5: %.5.xml
	${XMLTO} man $<

%.1: %.1.xml
	${XMLTO} man $<
endif



