# xmlto is from http://cyberelk.net/tim/xmlto/
ifneq ($(strip $(XMLTO)),)
%.8: %.8.xml
	${XMLTO} man $<

%.8.html: %.8.xml
	${XMLTO} html-nochunks $<

%.5: %.5.xml
	${XMLTO} man $<

%.1: %.1.xml
	${XMLTO} man $<
endif

# ronn is from https://rtomayko.github.io/ronn/
ifneq ($(strip $(RONN)),)
%.8: %.8.ronn
	${RONN} --roff $<

%.8.html: %.8.ronn
	${RONN} --html $<

%.5: %.5.ronn
	${RONN} --roff $<

%.1: %.1.ronn
	${RONN} --roff $<
endif





